### ISSUE TITLE
It is causing crash on different devices

### ISSUE THREAD

**Issue by Mamtak** [JcMinarro/RoundKornerLayouts#28]
Hi I am using RoundKornerFrameLayout.kt to draw circle at runtime. But it is causing crash on different device. I am using Version 0.3.1

I am attaching crash Report below:

`Fatal Exception: java.lang.RuntimeException: Canvas: trying to draw too large(132710400bytes) bitmap.
       at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1415)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:528)
       at android.view.View.getDrawableRenderNode(View.java:17432)
       at android.view.View.drawBackground(View.java:17368)
       at android.view.View.draw(View.java:17180)
       at android.view.View.updateDisplayListIfDirty(View.java:16171)
       at android.view.View.draw(View.java:16955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at com.jcminarro.roundkornerlayout.RoundKornerFrameLayout.access$dispatchDraw$s-398155364(RoundKornerFrameLayout.kt:9)
       at com.jcminarro.roundkornerlayout.RoundKornerFrameLayout$dispatchDraw$1.invoke(RoundKornerFrameLayout.kt:32)
       at com.jcminarro.roundkornerlayout.RoundKornerFrameLayout$dispatchDraw$1.invoke(RoundKornerFrameLayout.kt:9)
       at com.jcminarro.roundkornerlayout.CanvasRounder.round(CanvasRounder.kt:19)
       at com.jcminarro.roundkornerlayout.RoundKornerFrameLayout.dispatchDraw(RoundKornerFrameLayout.kt:32)
       at android.view.View.updateDisplayListIfDirty(View.java:16166)
       at android.view.View.draw(View.java:16955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16166)
       at android.view.View.draw(View.java:16955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16166)
       at android.view.View.draw(View.java:16955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1366)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17192)
       at android.view.View.updateDisplayListIfDirty(View.java:16171)
       at android.view.View.draw(View.java:16955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16166)
       at android.view.View.draw(View.java:16955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16166)
       at android.view.View.draw(View.java:16955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16166)
       at android.view.View.draw(View.java:16955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.updateDisplayListIfDirty(View.java:16166)
       at android.view.View.draw(View.java:16955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
       at android.view.View.draw(View.java:17192)
       at com.android.internal.policy.DecorView.draw(DecorView.java:789)
       at android.view.View.updateDisplayListIfDirty(View.java:16171)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3268)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3070)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2677)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1716)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6903)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:621)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6228)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by Mamtak** [comment]
I am not adding drawable to RoundCornerFrameLayout library. I am just converting FrameLayout to Circle and then Rectangle at runtime.
